name             'xigpi'
maintainer       'Jeff Barrows'
maintainer_email 'jeff@lmnt.co'
license          'All rights reserved'
description      'Installs/Configures xigpi'
long_description 'Installs/Configures xigpi'
version          '0.1.0'

depends 'apt'
depends 'monit-ng'
